import heroImage from '@/assets/coffee-hero.jpg';
import pourImage from '@/assets/coffee-pour.jpg';
import filterImage from '@/assets/coffee-filter.jpg';
import beansImage from '@/assets/coffee-beans.jpg';

export const chapters = [
  { slug: 'the-beginning', title: 'The beginning', kicker: 'Where the day begins', line: 'Every cup starts somewhere.', description: 'Before the first sip, there is a pause. A kitchen waking up, the sound of a lid lifting, and the promise of something worth slowing down for.', detail: 'Filter coffee is more than a way to wake up. It is a small daily ceremony, built from simple things and repeated with care.', image: heroImage, imageAlt: 'Frothy filter coffee in a steel tumbler and davara', category: 'The ritual' },
  { slug: 'the-land', title: 'The land', kicker: 'From soil to story', line: 'It starts in the shade.', description: 'Coffee grows across the lush hills of southern India, where shade trees, rain, and patient hands shape the character of every harvest.', detail: 'The story of a cup begins long before the water boils. It begins with a landscape and the people who tend it.', image: beansImage, imageAlt: 'Roasted coffee beans beside green coffee leaves', category: 'The origins' },
  { slug: 'the-bean', title: 'The bean', kicker: 'A little character', line: 'Small bean. Big feeling.', description: 'Arabica brings fragrance and softness. Robusta lends strength and body. Together, they make a cup that knows exactly who it is.', detail: 'There is no single perfect blend. The beauty lies in finding the balance that feels like home to you.', image: beansImage, imageAlt: 'A bowl of roasted coffee beans scattered on a red surface', category: 'The ingredients' },
  { slug: 'the-roast', title: 'The roast', kicker: 'Heat changes everything', line: 'A deeper kind of warmth.', description: 'Roasting draws out the bean’s hidden notes, turning the raw and grassy into something fragrant, dark, and unmistakably inviting.', detail: 'Listen closely: the aroma changes as the roast develops. The best cups begin with attention to those little changes.', image: beansImage, imageAlt: 'Sunlit roasted coffee beans', category: 'The ingredients' },
  { slug: 'the-grind', title: 'The grind', kicker: 'Made for the filter', line: 'It is all in the texture.', description: 'A fine, even grind helps water find its way through the coffee slowly, gathering the flavor that will become the heart of the cup.', detail: 'Grind just before brewing when you can. That freshly opened aroma is part of the experience.', image: filterImage, imageAlt: 'Coffee grounds beside a traditional metal coffee filter', category: 'The method' },
  { slug: 'the-filter', title: 'The filter', kicker: 'A humble invention', line: 'Two chambers. One quiet marvel.', description: 'A traditional metal filter asks for no electricity and no hurry. Grounds sit above; rich coffee collects below, one drop at a time.', detail: 'Its familiar shape belongs on kitchen shelves and breakfast tables. Simple tools have a way of lasting.', image: filterImage, imageAlt: 'Traditional stainless steel South Indian coffee filter', category: 'The method' },
  { slug: 'the-decoction', title: 'The decoction', kicker: 'The heart of the cup', line: 'Good things take their time.', description: 'Hot water settles into the grounds and slowly becomes a dark, concentrated decoction. This is the strong little secret behind every cup.', detail: 'Let gravity do its work. The waiting is not a delay; it is the recipe.', image: filterImage, imageAlt: 'Metal coffee filter with freshly ground coffee', category: 'The method' },
  { slug: 'the-milk', title: 'The milk', kicker: 'A soft counterpoint', line: 'Strength meets softness.', description: 'Warm milk rounds out the intensity of the decoction, creating the familiar balance of bold coffee and gentle sweetness.', detail: 'The ratio is personal. Make it strong, make it mellow, or keep finding your own middle ground.', image: heroImage, imageAlt: 'Milky froth rising above a steel coffee tumbler', category: 'The cup' },
  { slug: 'the-pour', title: 'The pour', kicker: 'The moment of movement', line: 'Let it fall. Let it sing.', description: 'Coffee travels between tumbler and davara in a long, graceful ribbon. It cools, it mixes, and a beautiful layer of froth appears.', detail: 'That unmistakable arc is as much a part of the experience as the taste. A little theatre, performed at breakfast.', image: pourImage, imageAlt: 'Filter coffee poured in a stream between steel vessels', category: 'The cup' },
  { slug: 'the-davara', title: 'The davara', kicker: 'A perfect pairing', line: 'Made to be held.', description: 'The tumbler and its shallow companion, the davara, are the iconic vessels of this ritual. They make room for the pour and the pause.', detail: 'Cool metal against your fingertips. Warm coffee on your lips. Some design details need no improvement.', image: heroImage, imageAlt: 'Steel tumbler set inside a davara saucer', category: 'The cup' },
  { slug: 'the-first-sip', title: 'The first sip', kicker: 'Worth the wait', line: 'And then, everything slows.', description: 'There is a moment when the cup reaches your lips and the rest of the morning can wait. This is the reason for all the little steps.', detail: 'Rich, warm, fragrant, and alive with texture. The first sip belongs entirely to you.', image: heroImage, imageAlt: 'Freshly made filter coffee with thick froth', category: 'The ritual' },
  { slug: 'the-table', title: 'The table', kicker: 'Better together', line: 'A cup makes room for company.', description: 'Coffee has a way of bringing people to the same table. Stories travel easily when there is something warm between two hands.', detail: 'Some cups are made for quiet. Others begin a conversation that lasts all afternoon.', image: pourImage, imageAlt: 'Hands preparing South Indian filter coffee', category: 'The culture' },
  { slug: 'make-your-own', title: 'Make your own', kicker: 'Your turn to brew', line: 'A ritual you can make yours.', description: 'Add ground coffee to the upper chamber, pour in hot water, wait for the decoction, then mix it with warm milk and pour to froth.', detail: 'Start with a couple of spoonfuls of coffee and adjust from there. The best recipe is the one you come back to.', image: filterImage, imageAlt: 'Coffee filter and grounds ready for brewing', category: 'The guide' },
  { slug: 'the-next-cup', title: 'The next cup', kicker: 'A story that continues', line: 'See you at the next pour.', description: 'The last drop is never quite the end. Tomorrow brings another morning, another chance to slow down, and another cup to make your own.', detail: 'Go back to the beginning, revisit a favorite chapter, or simply carry the feeling with you.', image: pourImage, imageAlt: 'A stream of fresh coffee falling into a steel tumbler', category: 'The ritual' },
] as const;

export type Chapter = (typeof chapters)[number];
export const chapterPath = '/chapters/$slug' as const;
